### ISSUE TITLE
No checks showing

### ISSUE THREAD

**Issue by schodemeiss** [sstarcher/docker-uchiwa#2]
Hello,

I've got my Sensu stack setup in Docker, and all my checks run correctly from the Server being Published to my client. I can even call my API via /clients and that shows me the clients attached. However - "/checks" appears empty.

I've checked all the logs, I can't see any errors. Everything seems to be correct, except the checks API not populating with my server based checks.

Any help would be appreciated.

**Comment by schodemeiss** [comment]
Ah, ok, I've found out.

So, if you're running the API and server separately (ALA, you have to due to the way these containers are setup), you MUST provide the sensu-api container with the same checks as the server (you can just mount the same files or copy them into your container, depending on how you're setting up).

This needs documenting pronto.

**Comment by sstarcher** [comment]
@schodemeiss That's based off the structure of sensu.  For the checks to show up in Uchiwa the Sensu API must have those checks locally.

**Comment by sstarcher** [comment]
@schodemeiss https://github.com/sstarcher/docker-uchiwa/commit/6c64e589ebfcc58a81f111242d8da0b6b844efc7#diff-04c6e90faac2675aa89e2176d2eec7d8
